//go:build strategist_payload && windows && arm64

package bundled

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/windows-arm64
var nodePayload embed.FS

func init() { registerTarget("windows-arm64", nodePayload) }
