//go:build strategist_payload && darwin && amd64

package runtimepayload

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/darwin-amd64
var nodePayload embed.FS

func init() { registerTarget("darwin-amd64", nodePayload) }
