//go:build strategist_payload && darwin && arm64

package runtimepayload

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/darwin-arm64
var nodePayload embed.FS

func init() { registerTarget("darwin-arm64", nodePayload) }
