//go:build strategist_payload && windows && amd64

package runtimepayload

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/windows-amd64
var nodePayload embed.FS

func init() { registerTarget("windows-amd64", nodePayload) }
