//go:build strategist_payload && linux && amd64

package runtimepayload

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/linux-amd64
var nodePayload embed.FS

func init() { registerTarget("linux-amd64", nodePayload) }
