//go:build strategist_payload && linux && arm64

package runtimepayload

import "embed"

// nodePayload holds this target's Node archive, generated by
// scripts/fetch-node-runtime.py (git-ignored, never hand-edited).
//
//go:embed nodepayload/linux-arm64
var nodePayload embed.FS

func init() { registerTarget("linux-arm64", nodePayload) }
