package runtimepayload

import "io/fs"

// Embedded is a payload compiled into the binary: the pinned manifest and the
// files it names.
type Embedded struct {
	Manifest Manifest
	FS       fs.FS
}

var embedded *Embedded

// Register installs the payload compiled into this binary. Build-tagged files
// generated by the release pipeline call it from init; ordinary builds and
// tests never do, so Default reports no payload for them.
func Register(m Manifest, src fs.FS) {
	if src == nil {
		embedded = nil
		return
	}
	embedded = &Embedded{Manifest: m, FS: src}
}

// Default returns the payload compiled into this binary, if any.
func Default() (Embedded, bool) {
	if embedded == nil {
		return Embedded{}, false
	}
	return *embedded, true
}
