package check

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	codexBootstrapRelPath = ".codex/commands.md"
	codexRuntimeSection   = "## Strategist Runtime Discovery"
	codexGeneratedMarker  = "<!-- generated by: strategist compile — do not edit manually -->"
)

// codexBootstrapAdvisories reports project-local CODEX seed drift without
// invoking CODEX or changing the blocking readiness decision. A project
// without a .codex directory is outside this diagnostic's scope.
func codexBootstrapAdvisories(root string) []string {
	projectRoot := root
	if filepath.Base(filepath.Clean(root)) == ".strategist" {
		projectRoot = filepath.Dir(root)
	}
	if warning, ok := codexDirAdvisory(projectRoot); !ok {
		return warning
	}
	return codexCommandsAdvisory(projectRoot)
}

// codexDirAdvisory inspects projectRoot's .codex/ directory. ok is false when
// codexBootstrapAdvisories should stop here: either .codex/ is absent (a
// project without CODEX seeding is outside this diagnostic's scope, warning
// is nil), or it exists but could not be inspected (warning carries that
// advisory).
func codexDirAdvisory(projectRoot string) (warning []string, ok bool) {
	codexDir := filepath.Join(projectRoot, ".codex")
	info, err := os.Stat(codexDir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false
	}
	if err != nil || !info.IsDir() {
		return []string{codexBootstrapWarning("codex_bootstrap_unreadable", codexDir, err)}, false
	}
	return nil, true
}

// codexCommandsAdvisory checks the CODEX seed file itself, once its parent
// directory is known to exist and be inspectable.
func codexCommandsAdvisory(projectRoot string) []string {
	commandsPath := filepath.Join(projectRoot, codexBootstrapRelPath)
	data, err := os.ReadFile(commandsPath) //nolint:gosec // path is derived from the selected project root
	if errors.Is(err, os.ErrNotExist) {
		return []string{codexBootstrapWarning("codex_bootstrap_missing", commandsPath, nil)}
	}
	if err != nil {
		return []string{codexBootstrapWarning("codex_bootstrap_unreadable", commandsPath, err)}
	}
	if !strings.Contains(string(data), codexRuntimeSection) || !strings.Contains(string(data), codexGeneratedMarker) {
		return []string{codexBootstrapWarning("codex_bootstrap_stale", commandsPath, nil)}
	}
	return nil
}

func codexBootstrapWarning(reason, path string, cause error) string {
	message := fmt.Sprintf("[Strategist] phase=preflight status=warn reason=%s path=%s", reason, path)
	if cause != nil {
		message += ": " + cause.Error()
	}
	return message + " (run `strategist compile` or reinstall to repair)"
}
