package compile

// Markdown-section seed upsert subtests (claude-instructions / codex commands /
// copilot), covering the uniform seedTargets loop in agent_awareness.go.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAgentAwareness(t *testing.T) {
	t.Parallel()

	t.Run("no-op when no agent files present", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		err := agentAwareness(dir)
		require.NoError(t, err)
	})

	t.Run("upserts claude-instructions section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		initial := "# Claude Instructions\n\n## My Section\n\nKeep this.\n"
		require.NoError(t, os.WriteFile(claudePath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(claudePath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## My Section")
		assert.Contains(t, s, "Keep this.")
	})

	t.Run("replaces existing claude-instructions section on second run", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		initial := "# Claude Instructions\n\n## Strategist Runtime Discovery\n\nOld awareness.\n\n## Other\n\nKeep.\n"
		require.NoError(t, os.WriteFile(claudePath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(claudePath)
		s := string(content)
		assert.NotContains(t, s, "Old awareness.")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "## Other")
		assert.Contains(t, s, "Keep.")
	})

	t.Run("upserts codex commands section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		codexCmdPath := filepath.Join(dir, ".codex", "commands.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(codexCmdPath), 0o755))
		initial := "# Codex Commands\n\n## Run Tests\n\ngo test ./...\n"
		require.NoError(t, os.WriteFile(codexCmdPath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(codexCmdPath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## Run Tests")
		assert.Contains(t, s, "go test ./...")
	})

	t.Run("codex commands section is idempotent", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		codexCmdPath := filepath.Join(dir, ".codex", "commands.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(codexCmdPath), 0o755))
		require.NoError(t, os.WriteFile(codexCmdPath, []byte("# Commands\n"), 0o644))

		require.NoError(t, agentAwareness(dir))
		first, _ := os.ReadFile(codexCmdPath)

		require.NoError(t, agentAwareness(dir))
		second, _ := os.ReadFile(codexCmdPath)

		assert.Equal(t, string(first), string(second), "second run must produce identical output")
	})

	t.Run("upserts copilot section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		copilotPath := filepath.Join(dir, ".github", "copilot-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(copilotPath), 0o755))
		initial := "# Copilot Instructions\n\n## Other Section\n\nKeep this.\n"
		require.NoError(t, os.WriteFile(copilotPath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(copilotPath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## Other Section")
		assert.Contains(t, s, "Keep this.")
	})

	t.Run("copilot section is idempotent", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		copilotPath := filepath.Join(dir, ".github", "copilot-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(copilotPath), 0o755))
		require.NoError(t, os.WriteFile(copilotPath, []byte("# Copilot\n"), 0o644))

		require.NoError(t, agentAwareness(dir))
		first, _ := os.ReadFile(copilotPath)

		require.NoError(t, agentAwareness(dir))
		second, _ := os.ReadFile(copilotPath)

		assert.Equal(t, string(first), string(second), "second run must produce identical output")
	})

	t.Run("generated section carries attribution marker", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		require.NoError(t, os.WriteFile(claudePath, []byte("# Claude Instructions\n"), 0o644))

		const marker = "<!-- generated by: strategist compile — do not edit manually -->"

		require.NoError(t, agentAwareness(dir))
		first, _ := os.ReadFile(claudePath)
		assert.Contains(t, string(first), marker)
		assert.Equal(t, 1, strings.Count(string(first), marker), "marker must appear exactly once")

		// Re-run against a file that already carries the marker (upsert path, not append)
		// to prove the marker is not duplicated on repeated compiles.
		require.NoError(t, agentAwareness(dir))
		second, _ := os.ReadFile(claudePath)
		assert.Equal(t, 1, strings.Count(string(second), marker), "marker must not duplicate across upserts")
		assert.Equal(t, string(first), string(second), "second run must produce identical output")
	})

	t.Run("error in one agent does not block others", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		// Create .agents/skills.json with invalid JSON so ideAwareness's skills.json
		// step will fail (requires .strategist/ to exist for ideAwareness to run).
		require.NoError(t, os.MkdirAll(filepath.Join(dir, ".strategist"), 0o755))
		require.NoError(t, os.MkdirAll(filepath.Join(dir, ".agents"), 0o755))
		require.NoError(t, os.WriteFile(filepath.Join(dir, ".agents", "skills.json"), []byte("not json"), 0o644))

		// Create a valid claude-instructions.md.
		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		require.NoError(t, os.WriteFile(claudePath, []byte("# Claude\n"), 0o644))

		// agentAwareness must not error even though .agents/skills.json failed.
		require.NoError(t, agentAwareness(dir))

		// Claude file must still have been updated.
		content, _ := os.ReadFile(claudePath)
		assert.Contains(t, string(content), "## Strategist Runtime Discovery")

		// AGENTS.md must still have been upserted despite the skills.json failure.
		agentsMD, _ := os.ReadFile(filepath.Join(dir, ".agents", "AGENTS.md"))
		assert.Contains(t, string(agentsMD), agentsRuntimeStartMarker)
	})
}
