package compile

import (
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

const strategistRuntimeDiscoverySection = `## Strategist Runtime Discovery

<!-- generated by: strategist compile — do not edit manually -->

The presence of ` + "`" + `.strategist/` + "`" + ` makes Strategist available; it does not activate a
Strategist mission. Handle an ordinary request directly unless the user explicitly invokes
Strategist through its dedicated skill, a registered host slash command, or a
` + "`" + `strategist mission` + "`" + ` CLI operation.

A reference to a path under ` + "`" + `.analysis/refined/` + "`" + ` does not activate a
mission. Local execution context is a precondition; it is not proof of
mission activation or approval. Only after explicit activation does the mission-only role lock apply.

` + "`" + `strategist check --json` + "`" + ` is a static preflight diagnostic. It does not invoke a
provider, start a mission, or authorize the Strategist pipeline.

After an explicit Strategist invocation, the parent agent MUST NOT solve that mission
directly — it is the orchestrator shell, not the implementer:

1. Run ` + "`" + `strategist check --json` + "`" + `, capture the PreflightResult — ` + "`" + `status == "blocked"` + "`" + `: emit ` + "`" + `warnings` + "`" + ` and stop
2. Read ` + "`" + `.strategist/agent-protocol.md` + "`" + ` — full role and pipeline protocol
3. Read ` + "`" + `.strategist/SKILL.md` + "`" + ` — contracts and path model
4. Read ` + "`" + `.strategist/skill.yaml` + "`" + ` — slot mapping

Mandatory restrictions after bootstrap:
- Do not skip phases unless the internal routing contract selected Critical Hit
- Do not perform source-code mutation; Strategist produces analysis, documentation, and handoff artifacts
- Route selection is internal to Strategist; invoke the skill with the request context
- If a configured slot/provider cannot be invoked, emit ` + "`" + `error=role_invocation_failed` + "`" + ` with slot and provider — do not fall back to solving the phase directly

When Strategist was explicitly invoked but ` + "`" + `.strategist/` + "`" + ` is absent:
→ emit ` + "`" + `error=not_installed` + "`" + `, instruct the user to run ` + "`" + `strategist install` + "`" + `, stop.

` + "`" + `A provisioned governance source` + "`" + ` is governance — it is not part of the Strategist runtime.
` + "`" + `.strategist/agent-protocol.md` + "`" + ` is the runtime authority for agent behavior.
Discovery contract: ` + "`" + `.strategist/provider-discovery.md` + "`"

// seedTargets lists the per-agent seed files agentAwareness upserts, uniformly,
// via the markdown section mechanism. One entry per supported coding-agent seed:
// CODEX, Claude, Copilot.
var seedTargets = []struct {
	relPath                string
	label                  string
	createWhenParentExists bool
}{
	{relPath: filepath.Join(".claude", "claude-instructions.md"), label: "claude-instructions"},
	{relPath: filepath.Join(".codex", "commands.md"), label: "codex commands", createWhenParentExists: true},
	{relPath: filepath.Join(".github", "copilot-instructions.md"), label: "copilot"},
}

// agentAwareness refreshes per-agent seed files at projectRoot, creating the
// CODEX seed only when its parent directory already exists. It then runs
// ideAwareness for IDE-level workspace registration. Failures per file are
// logged and skipped — this function always returns nil (non-blocking by
// contract).
func agentAwareness(projectRoot string) error {
	for _, t := range seedTargets {
		upsertSeed(filepath.Join(projectRoot, t.relPath), t.createWhenParentExists, upsertSection, t.label)
	}
	return ideAwareness(projectRoot)
}

func upsertSeed(path string, createWhenParentExists bool, update func(string) error, label string) {
	if !seedReady(path, createWhenParentExists, label) {
		return
	}
	if err := update(path); err != nil {
		slog.Warn("[Strategist] agent awareness: "+label+" update failed", "error", err)
	}
}

// seedReady reports whether path is an existing seed file ready to be
// upserted, creating it first when createWhenParentExists and its parent
// directory already exists. Failures are logged and treated as "not
// ready" (non-blocking by contract).
func seedReady(path string, createWhenParentExists bool, label string) bool {
	info, err := os.Stat(path)
	switch {
	case err == nil && !info.IsDir():
		return true
	case errors.Is(err, os.ErrNotExist) && createWhenParentExists:
		return createSeedFile(path, label)
	case errors.Is(err, os.ErrNotExist):
		return false
	default:
		slog.Warn("[Strategist] agent awareness: "+label+" stat failed", "error", err)
		return false
	}
}

func createSeedFile(path, label string) bool {
	parentInfo, parentErr := os.Stat(filepath.Dir(path))
	if parentErr != nil || !parentInfo.IsDir() {
		return false
	}
	if err := writeFile(path, nil, label); err != nil {
		slog.Warn("[Strategist] agent awareness: "+label+" create failed", "error", err)
		return false
	}
	return true
}

// RefreshAgentAwareness is the single coordinating entry point for both the
// compile command and the install wizard/silent paths.
// tplBytes is the content of the agent-protocol.md template (read by the caller
// from the embed FS so this package does not depend on internal/embed).
// It generates or upserts <strategistRoot>/agent-protocol.md and then runs
// AgentAwareness for all per-agent entrypoint files.
// All sub-steps are non-blocking: failures are logged as warnings.
// Returns whether agent-protocol.md was successfully written, for caller output.
func RefreshAgentAwareness(strategistRoot, projectRoot, version string, tplBytes []byte) (protocolOK bool) {
	if len(tplBytes) == 0 {
		slog.Warn("[Strategist] agent-protocol template not found or empty")
	} else if err := agentProtocol(strategistRoot, tplBytes, version); err != nil {
		slog.Warn("[Strategist] agent-protocol generation failed", "error", err)
	} else {
		protocolOK = true
	}

	if err := agentAwareness(projectRoot); err != nil {
		slog.Warn("[Strategist] agent awareness update skipped", "error", err)
	}

	return protocolOK
}

// upsertSection replaces the "## Strategist Runtime Discovery" section in path.
// If the section is absent, appends it. Other content is preserved.
// Used for all markdown-based agent seed files (claude, codex commands, copilot).
func upsertSection(path string) error {
	data, err := os.ReadFile(path) //nolint:gosec // G304: path derived from projectRoot
	if err != nil {
		return fmt.Errorf("upsert section: read %s: %w", path, err)
	}

	content := string(data)
	const sectionHeader = "## Strategist Runtime Discovery"
	content = upsertMarkdownSection(content, sectionHeader, strategistRuntimeDiscoverySection)
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return writeFile(path, []byte(content), "upsert section")
}

func upsertMarkdownSection(content, sectionHeader, newSection string) string {
	idx := strings.Index(content, sectionHeader)
	if idx == -1 {
		return appendMarkdownSection(content, newSection)
	}
	after := content[idx+len(sectionHeader):]
	return content[:idx] + newSection + markdownTail(after)
}

func appendMarkdownSection(content, newSection string) string {
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + "\n" + newSection + "\n"
}

func markdownTail(after string) string {
	idx := indexNextHeading(after)
	if idx == -1 {
		return ""
	}
	return after[idx:]
}

// indexNextHeading finds the index of the "\n" immediately preceding the next
// Markdown heading line (any level, "#" through "######") in s, or -1 if none
// exists. Only lines after the first are considered, since s is the content
// immediately following a section header, not itself a heading line.
func indexNextHeading(s string) int {
	lines := strings.Split(s, "\n")
	offset := 0
	for i, line := range lines {
		if i > 0 && strings.HasPrefix(line, "#") {
			return offset - 1
		}
		offset += len(line) + 1
	}
	return -1
}

// ideAwareness, upsertAgentsSkillsJSON, readAgentsSkillsDoc,
// upsertAgentsMarkdown, and upsertDelimitedSection (the .agents/ IDE
// workspace-registration mechanism) live in ide_awareness.go, split out to
// keep this file under the repo's file-size budget.
