package compile

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

const strategistRuntimeDiscoverySection = `## Strategist Runtime Discovery

<!-- generated by: strategist compile — do not edit manually -->

When ` + "`" + `.strategist/` + "`" + ` is present in the workspace, Strategist is active. The parent
agent MUST NOT solve the user's task directly — it is the orchestrator shell, not the
implementer:

1. Run ` + "`" + `strategist check` + "`" + ` — if it fails: emit the CLI output and stop
2. Read ` + "`" + `.strategist/agent-protocol.md` + "`" + ` — full role and pipeline protocol
3. Read ` + "`" + `.strategist/SKILL.md` + "`" + ` — contracts and path model
4. Read ` + "`" + `.strategist/skill.yaml` + "`" + ` — slot mapping

Mandatory restrictions after bootstrap:
- Do not skip phases unless the internal routing contract selected Critical Hit
- Do not perform source-code mutation; Strategist produces analysis, documentation, and handoff artifacts
- Route selection is internal to Strategist; invoke the skill with the request context
- If a configured slot/provider cannot be invoked, emit ` + "`" + `error=role_invocation_failed` + "`" + ` with slot and provider — do not fall back to solving the phase directly

When ` + "`" + `.strategist/` + "`" + ` is absent:
→ emit ` + "`" + `error=not_installed` + "`" + `, instruct the user to run ` + "`" + `strategist install` + "`" + `, stop.

` + "`" + `.sdd/` + "`" + ` is governance — it is not part of the Strategist runtime.
` + "`" + `.strategist/agent-protocol.md` + "`" + ` is the runtime authority for agent behavior.
Discovery contract: ` + "`" + `.strategist/provider-discovery.md` + "`"

// seedTargets lists the per-agent seed files agentAwareness upserts, uniformly,
// via the markdown section mechanism. One entry per supported coding-agent seed:
// CODEX, Claude, Copilot.
var seedTargets = []struct {
	relPath string
	label   string
}{
	{filepath.Join(".claude", "claude-instructions.md"), "claude-instructions"},
	{filepath.Join(".codex", "commands.md"), "codex commands"},
	{filepath.Join(".github", "copilot-instructions.md"), "copilot"},
}

// agentAwareness upserts per-agent seed files at projectRoot if they already exist,
// then runs ideAwareness for IDE-level workspace registration. Does not create seed
// files that do not exist. Failures per file are logged and skipped — this function
// always returns nil (non-blocking by contract).
func agentAwareness(projectRoot string) error {
	for _, t := range seedTargets {
		upsertIfExists(filepath.Join(projectRoot, t.relPath), upsertSection, t.label)
	}
	return ideAwareness(projectRoot)
}

func upsertIfExists(path string, update func(string) error, label string) {
	if _, err := os.Stat(path); err != nil {
		return
	}
	if err := update(path); err != nil {
		slog.Warn("[Strategist] agent awareness: "+label+" update failed", "error", err)
	}
}

// RefreshAgentAwareness is the single coordinating entry point for both the
// compile command and the install wizard/silent paths.
// tplBytes is the content of the agent-protocol.md template (read by the caller
// from the embed FS so this package does not depend on internal/embed).
// It generates or upserts <strategistRoot>/agent-protocol.md and then runs
// AgentAwareness for all per-agent entrypoint files.
// All sub-steps are non-blocking: failures are logged as warnings.
// Returns whether agent-protocol.md was successfully written, for caller output.
func RefreshAgentAwareness(strategistRoot, projectRoot, version string, tplBytes []byte) (protocolOK bool) {
	if len(tplBytes) == 0 {
		slog.Warn("[Strategist] agent-protocol template not found or empty")
	} else if err := agentProtocol(strategistRoot, tplBytes, version); err != nil {
		slog.Warn("[Strategist] agent-protocol generation failed", "error", err)
	} else {
		protocolOK = true
	}

	if err := agentAwareness(projectRoot); err != nil {
		slog.Warn("[Strategist] agent awareness update skipped", "error", err)
	}

	return protocolOK
}

// upsertSection replaces the "## Strategist Runtime Discovery" section in path.
// If the section is absent, appends it. Other content is preserved.
// Used for all markdown-based agent seed files (claude, codex commands, copilot).
func upsertSection(path string) error {
	data, err := os.ReadFile(path) //nolint:gosec // G304: path derived from projectRoot
	if err != nil {
		return fmt.Errorf("upsert section: read %s: %w", path, err)
	}

	content := string(data)
	const sectionHeader = "## Strategist Runtime Discovery"
	content = upsertMarkdownSection(content, sectionHeader, strategistRuntimeDiscoverySection)
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return writeFile(path, []byte(content), "upsert section")
}

func upsertMarkdownSection(content, sectionHeader, newSection string) string {
	idx := strings.Index(content, sectionHeader)
	if idx == -1 {
		return appendMarkdownSection(content, newSection)
	}
	after := content[idx+len(sectionHeader):]
	return content[:idx] + newSection + markdownTail(after)
}

func appendMarkdownSection(content, newSection string) string {
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + "\n" + newSection + "\n"
}

func markdownTail(after string) string {
	idx := indexNextHeading(after)
	if idx == -1 {
		return ""
	}
	return after[idx:]
}

// indexNextHeading finds the index of the "\n" immediately preceding the next
// Markdown heading line (any level, "#" through "######") in s, or -1 if none
// exists. Only lines after the first are considered, since s is the content
// immediately following a section header, not itself a heading line.
func indexNextHeading(s string) int {
	lines := strings.Split(s, "\n")
	offset := 0
	for i, line := range lines {
		if i > 0 && strings.HasPrefix(line, "#") {
			return offset - 1
		}
		offset += len(line) + 1
	}
	return -1
}

const (
	agentsRuntimeStartMarker = "<!-- strategist-runtime-start -->"
	agentsRuntimeEndMarker   = "<!-- strategist-runtime-end -->"
	strategistEntryPath      = ".strategist"
)

// ideAwareness registers the .strategist runtime with IDEs that discover skills
// via a workspace customizations root, when .strategist/ exists at projectRoot.
// Currently only Antigravity needs this — VSCode already discovers the Claude
// seed natively via its extension, so it needs no additional registration.
// Non-blocking: all failures are logged and skipped.
func ideAwareness(projectRoot string) error {
	if _, err := os.Stat(filepath.Join(projectRoot, ".strategist")); err != nil {
		return nil
	}

	agentsDir := filepath.Join(projectRoot, ".agents")
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return fmt.Errorf("ide awareness: mkdir %s: %w", agentsDir, err)
	}

	if err := upsertAgentsSkillsJSON(filepath.Join(agentsDir, "skills.json")); err != nil {
		slog.Warn("[Strategist] ide awareness: skills.json update failed", "error", err)
	}
	if err := upsertAgentsMarkdown(filepath.Join(agentsDir, "AGENTS.md")); err != nil {
		slog.Warn("[Strategist] ide awareness: AGENTS.md update failed", "error", err)
	}
	return nil
}

// upsertAgentsSkillsJSON ensures {"path": ".strategist"} is present in the
// entries array of the .agents/skills.json registry, creating the file if
// absent and preserving any other entries and top-level keys already present.
func upsertAgentsSkillsJSON(path string) error {
	doc, err := readAgentsSkillsDoc(path)
	if err != nil {
		return err
	}

	entries, ok := doc["entries"].([]any)
	if !ok {
		entries = nil
	}
	for _, e := range entries {
		if m, ok := e.(map[string]any); ok && m["path"] == strategistEntryPath {
			return nil // already registered, nothing to write
		}
	}
	doc["entries"] = append(entries, map[string]any{"path": strategistEntryPath})

	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return fmt.Errorf("agents skills.json: marshal %s: %w", path, err)
	}
	return writeFile(path, append(out, '\n'), "agents skills.json")
}

func readAgentsSkillsDoc(path string) (map[string]any, error) {
	data, err := os.ReadFile(path) //nolint:gosec // G304: path derived from projectRoot
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]any{}, nil
		}
		return nil, fmt.Errorf("agents skills.json: read %s: %w", path, err)
	}

	doc := map[string]any{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("agents skills.json: parse %s: %w", path, err)
	}
	return doc, nil
}

// upsertAgentsMarkdown upserts the delimited Strategist Runtime Discovery block
// into .agents/AGENTS.md. Creates the file with a minimal header if absent.
// If the delimiters are absent from existing content, appends the block.
func upsertAgentsMarkdown(path string) error {
	data, err := os.ReadFile(path) //nolint:gosec // G304: path derived from projectRoot
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("agents markdown: read %s: %w", path, err)
		}
		data = []byte("# Agent Rules\n")
	}

	content := upsertDelimitedSection(string(data), agentsRuntimeStartMarker, agentsRuntimeEndMarker, strategistRuntimeDiscoverySection)
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return writeFile(path, []byte(content), "agents markdown")
}

// upsertDelimitedSection replaces the content between startMarker and endMarker
// with newBlock, wrapped in the markers. If the markers are absent (or malformed —
// end before start), a new delimited block is appended to the end of content.
func upsertDelimitedSection(content, startMarker, endMarker, newBlock string) string {
	startIdx := strings.Index(content, startMarker)
	endIdx := strings.Index(content, endMarker)
	block := startMarker + "\n" + newBlock + "\n" + endMarker

	if startIdx == -1 || endIdx == -1 || endIdx < startIdx {
		if !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		return content + "\n" + block + "\n"
	}
	return content[:startIdx] + block + content[endIdx+len(endMarker):]
}
