package compile

// Markdown-section upsert subtests (antigravity / claude-instructions / codex
// commands), split from the JSON codex-seed subtests in
// agent_awareness_codexseed_test.go. Moved to package compile alongside the
// AgentAwareness -> agentAwareness unexport.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAgentAwareness(t *testing.T) {
	t.Parallel()

	t.Run("no-op when no agent files present", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()
		err := agentAwareness(dir)
		require.NoError(t, err)
	})

	t.Run("upserts antigravity section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		agPath := filepath.Join(dir, ".antigravity", "antigravity-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(agPath), 0o755))
		initial := "# Antigravity Instructions\n\n## Strategist Runtime Discovery\n\nOld content here.\n\n## Other Section\n\nKeep this.\n"
		require.NoError(t, os.WriteFile(agPath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(agPath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.NotContains(t, s, "Old content here.")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## Other Section")
		assert.Contains(t, s, "Keep this.")
		assert.Contains(t, s, "Route selection is internal to Strategist")
		assert.Contains(t, s, "Strategist produces analysis, documentation, and handoff artifacts")
	})

	t.Run("appends strategist section to antigravity when section absent", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		agPath := filepath.Join(dir, ".antigravity", "antigravity-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(agPath), 0o755))
		initial := "# Antigravity Instructions\n\n## Other Section\n\nContent.\n"
		require.NoError(t, os.WriteFile(agPath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(agPath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## Other Section")
	})

	t.Run("upserts claude-instructions section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		initial := "# Claude Instructions\n\n## My Section\n\nKeep this.\n"
		require.NoError(t, os.WriteFile(claudePath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(claudePath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## My Section")
		assert.Contains(t, s, "Keep this.")
	})

	t.Run("replaces existing claude-instructions section on second run", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		initial := "# Claude Instructions\n\n## Strategist Runtime Discovery\n\nOld awareness.\n\n## Other\n\nKeep.\n"
		require.NoError(t, os.WriteFile(claudePath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(claudePath)
		s := string(content)
		assert.NotContains(t, s, "Old awareness.")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "## Other")
		assert.Contains(t, s, "Keep.")
	})

	t.Run("upserts codex commands section when file exists", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		codexCmdPath := filepath.Join(dir, ".codex", "commands.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(codexCmdPath), 0o755))
		initial := "# Codex Commands\n\n## Run Tests\n\ngo test ./...\n"
		require.NoError(t, os.WriteFile(codexCmdPath, []byte(initial), 0o644))

		require.NoError(t, agentAwareness(dir))

		content, _ := os.ReadFile(codexCmdPath)
		s := string(content)
		assert.Contains(t, s, "## Strategist Runtime Discovery")
		assert.Contains(t, s, "strategist check")
		assert.Contains(t, s, "agent-protocol.md")
		assert.Contains(t, s, "## Run Tests")
		assert.Contains(t, s, "go test ./...")
	})

	t.Run("generated section carries attribution marker", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		agPath := filepath.Join(dir, ".antigravity", "antigravity-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(agPath), 0o755))
		require.NoError(t, os.WriteFile(agPath, []byte("# Antigravity Instructions\n"), 0o644))

		const marker = "<!-- generated by: strategist compile — do not edit manually -->"

		require.NoError(t, agentAwareness(dir))
		first, _ := os.ReadFile(agPath)
		assert.Contains(t, string(first), marker)
		assert.Equal(t, 1, strings.Count(string(first), marker), "marker must appear exactly once")

		// Re-run against a file that already carries the marker (upsert path, not append)
		// to prove the marker is not duplicated on repeated compiles.
		require.NoError(t, agentAwareness(dir))
		second, _ := os.ReadFile(agPath)
		assert.Equal(t, 1, strings.Count(string(second), marker), "marker must not duplicate across upserts")
		assert.Equal(t, string(first), string(second), "second run must produce identical output")
	})

	t.Run("codex commands section is idempotent", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		codexCmdPath := filepath.Join(dir, ".codex", "commands.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(codexCmdPath), 0o755))
		require.NoError(t, os.WriteFile(codexCmdPath, []byte("# Commands\n"), 0o644))

		require.NoError(t, agentAwareness(dir))
		first, _ := os.ReadFile(codexCmdPath)

		require.NoError(t, agentAwareness(dir))
		second, _ := os.ReadFile(codexCmdPath)

		assert.Equal(t, string(first), string(second), "second run must produce identical output")
	})

	t.Run("error in one agent does not block others", func(t *testing.T) {
		t.Parallel()
		dir := t.TempDir()

		// Create codex seed with invalid JSON so it will fail.
		codexPath := filepath.Join(dir, ".sdd", "seedlings", "codex.seed.json")
		require.NoError(t, os.MkdirAll(filepath.Dir(codexPath), 0o755))
		require.NoError(t, os.WriteFile(codexPath, []byte("not json"), 0o644))

		// Create a valid claude-instructions.md.
		claudePath := filepath.Join(dir, ".claude", "claude-instructions.md")
		require.NoError(t, os.MkdirAll(filepath.Dir(claudePath), 0o755))
		require.NoError(t, os.WriteFile(claudePath, []byte("# Claude\n"), 0o644))

		// agentAwareness must not error even though codex failed.
		require.NoError(t, agentAwareness(dir))

		// Claude file must still have been updated.
		content, _ := os.ReadFile(claudePath)
		assert.Contains(t, string(content), "## Strategist Runtime Discovery")
	})
}
