package install

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

func catalogHasDrifted(existingPath, wantPath string) (bool, error) {
	existing, err := os.ReadFile(existingPath) //nolint:gosec // G304: fixed, caller-configured repo-relative path
	if err != nil {
		return false, fmt.Errorf("check embedded drift: read %s: %w", existingPath, err)
	}
	want, err := os.ReadFile(wantPath) //nolint:gosec // G304: wantPath is generated by this same package into a freshly created temp dir
	if err != nil {
		return false, fmt.Errorf("check embedded drift: read %s: %w", wantPath, err)
	}
	return string(want) != string(existing), nil
}

func mirrorsHaveDrifted(ingested []IngestedSkill, defaultsRoot, tmpRoot string) (bool, error) {
	for _, skill := range ingested {
		wantDir := filepath.Join(tmpRoot, "skills", skill.ID)
		gotDir := filepath.Join(defaultsRoot, "skills", skill.ID)
		drifted, err := directoriesHaveDrifted(wantDir, gotDir)
		if err != nil {
			return false, fmt.Errorf("check embedded drift: compare %s and %s: %w", wantDir, gotDir, err)
		}
		if drifted {
			return true, nil
		}
	}
	return false, nil
}

func directoriesHaveDrifted(wantDir, gotDir string) (bool, error) {
	wantFiles, err := regularFiles(wantDir)
	if err != nil {
		return false, fmt.Errorf("list expected package %s: %w", wantDir, err)
	}
	gotFiles, err := regularFiles(gotDir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return true, nil
		}
		return false, fmt.Errorf("list installed package %s: %w", gotDir, err)
	}
	if len(wantFiles) != len(gotFiles) {
		return true, nil
	}
	matching, err := packageFilesMatch(wantFiles, gotFiles)
	if err != nil {
		return false, err
	}
	return !matching, nil
}

func packageFilesMatch(wantFiles, gotFiles map[string]string) (bool, error) {
	for rel, wantPath := range wantFiles {
		gotPath, ok := gotFiles[rel]
		if !ok {
			return false, nil
		}
		equal, err := filesEqual(wantPath, gotPath)
		if err != nil {
			return false, err
		}
		if !equal {
			return false, nil
		}
	}
	return true, nil
}

func filesEqual(wantPath, gotPath string) (bool, error) {
	want, err := os.ReadFile(wantPath) //nolint:gosec // paths are below generated package roots
	if err != nil {
		return false, fmt.Errorf("read expected file %s: %w", wantPath, err)
	}
	got, err := os.ReadFile(gotPath) //nolint:gosec // paths are below generated package roots
	if err != nil {
		return false, fmt.Errorf("read installed file %s: %w", gotPath, err)
	}
	return string(want) == string(got), nil
}

func regularFiles(root string) (map[string]string, error) {
	files := make(map[string]string)
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		rel, include, err := regularFilePath(root, path, entry, walkErr)
		if err != nil {
			return err
		}
		if include {
			files[rel] = path
		}
		return nil
	})
	if err != nil {
		return files, fmt.Errorf("walk %s: %w", root, err)
	}
	return files, nil
}

func regularFilePath(root, path string, entry os.DirEntry, walkErr error) (string, bool, error) {
	if walkErr != nil {
		return "", false, walkErr
	}
	if entry.IsDir() {
		return "", false, nil
	}
	if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() {
		return "", false, fmt.Errorf("unsupported package entry: %s", path)
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return "", false, fmt.Errorf("relative path for %s: %w", path, err)
	}
	return rel, true, nil
}

func lockHasDrifted(existingLockPath, wantLockPath string, hasIngested bool) (bool, error) {
	existing, err := os.ReadFile(existingLockPath) //nolint:gosec // G304: fixed, caller-configured repo-relative path
	if err != nil {
		return hasIngested, nil // missing lock is drift only when there is something to lock
	}
	want, err := os.ReadFile(wantLockPath) //nolint:gosec // G304: wantLockPath is generated by this same package into a freshly created temp dir
	if err != nil {
		return false, fmt.Errorf("check embedded drift: read %s: %w", wantLockPath, err)
	}
	return string(want) != string(existing), nil
}
