package install

import (
	"fmt"
	"os"
	"path/filepath"
)

const shimContent = `# Strategist skill — agent shim
# Installed by: strategist install
# This file registers the Strategist skill with your Claude agent.
# Do not edit this file manually.

skill: strategist
source: ~/.strategist
`

// installShim creates ~/.claude/skills/strategist/SKILL.md pointing to the
// installed skill, mirroring the behaviour of install_agent_shims() in install.sh.
func installShim(target string) error {
	_ = target // reserved for future multi-root shim support

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("home dir: %w", err)
	}
	return installShimTo(home)
}

// installShimTo writes the shim files under homeDir. Separated from installShim
// to allow injecting an arbitrary home directory in tests.
func installShimTo(homeDir string) error {
	shimDir := filepath.Join(homeDir, ".claude", "skills", "strategist")
	if err := os.MkdirAll(shimDir, 0o755); err != nil {
		return fmt.Errorf("mkdir shim dir: %w", err)
	}

	shimPath := filepath.Join(shimDir, "SKILL.md")
	if err := os.WriteFile(shimPath, []byte(shimContent), 0o644); err != nil {
		return fmt.Errorf("write shim: %w", err)
	}

	return nil
}
