package install

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/SergioLacerda/strategist-skill/internal/domain"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

const scaffoldSkillMD = "---\nname: demo-weapon\ndescription: demo\nmetadata:\n  version: \"2.0.0\"\n---\n\n# Demo\n"

func scaffoldPackage(t *testing.T, skillMD string) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "demo-weapon")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	if skillMD != "" {
		require.NoError(t, os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(skillMD), 0o644))
	}
	return dir
}

func scaffoldErrorCode(t *testing.T, err error) string {
	t.Helper()
	var scaffoldErr *SidecarScaffoldError
	require.ErrorAs(t, err, &scaffoldErr)
	return scaffoldErr.Code
}

func TestScaffoldSidecarDiscoveryEmbeddedDefaults(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)

	result, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}})

	require.NoError(t, err)
	assert.Equal(t, SidecarCreated, result.Status)
	raw, err := os.ReadFile(filepath.Join(dir, "strategist.yaml"))
	require.NoError(t, err)
	assert.Contains(t, string(raw), "# Generated by strategist plugins scaffold-sidecar v1; inputs: sha256:")

	// The generated file is what ingestion would load: it must pass the real adapter validation.
	adapter, err := loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.Equal(t, "2.0.0", adapter.Version)
	assert.Equal(t, "ranger", adapter.CanonicalRole)
	assert.Equal(t, []string{"ranger"}, adapter.Roles)
	assert.Equal(t, []string{"discovery"}, adapter.SupportedSlots)
	assert.Equal(t, "write_analysis", adapter.RiskScore)
	assert.Equal(t, "discovery", adapter.Category)
	assert.Equal(t, domain.WeaponKindAtomic, adapter.Kind)
	assert.False(t, adapter.Default)
	assert.Equal(t, domain.RankedRuntimeEmbedded, adapter.Runtime.Kind)
	assert.Equal(t, domain.WeaponExecutionModePromptBridge, adapter.Runtime.ExecutionMode)
	assert.Equal(t, "ranger", adapter.WeaponContract.RoleOwner)
	assert.Empty(t, adapter.UpstreamRepo, "provenance is never invented")
}

func TestScaffoldSidecarVersionFallsBackToTheDeclaredFlagOnly(t *testing.T) {
	noVersion := "---\nname: demo-weapon\n---\n"

	dir := scaffoldPackage(t, noVersion)
	_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}, Version: "1.0.0"})
	require.NoError(t, err)
	adapter, err := loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.Equal(t, "1.0.0", adapter.Version)

	// The package's own metadata.version always wins over the flag.
	dir = scaffoldPackage(t, scaffoldSkillMD)
	_, err = ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}, Version: "9.9.9"})
	require.NoError(t, err)
	adapter, err = loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.Equal(t, "2.0.0", adapter.Version)
}

func TestScaffoldSidecarRefinementOmitsTheRangerWeaponContract(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)

	_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"archivist"}, Slots: []string{"refinement"}, Default: true})

	require.NoError(t, err)
	adapter, err := loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.True(t, adapter.Default)
	assert.True(t, adapter.WeaponContract.IsZero())
	assert.Equal(t, "refinement", adapter.Category)
}

func TestScaffoldSidecarExecutionUsesControlledRisk(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)

	_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"sniper"}, Slots: []string{"execution"}})

	require.NoError(t, err)
	adapter, err := loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.Equal(t, "controlled", adapter.RiskScore)
}

func TestScaffoldSidecarRejectsInvalidDeclarations(t *testing.T) {
	cases := []struct {
		name  string
		skill string
		opts  SidecarScaffoldOptions
		code  string
	}{
		{"missing SKILL.md", "", SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"discovery"}}, "skill_md_missing"},
		{"missing version", "---\nname: demo-weapon\n---\n", SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"discovery"}}, "version_missing"},
		{"unknown role", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"wizard"}, Slots: []string{"discovery"}}, "role_unknown"},
		{"unknown slot", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"nowhere"}}, "slot_unknown"},
		{"role does not own slot", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"refinement"}}, "role_slot_mismatch"},
		{"no roles", scaffoldSkillMD, SidecarScaffoldOptions{Slots: []string{"discovery"}}, "role_unknown"},
		{"no slots", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"ranger"}}, "slot_unknown"},
		{"mixed risk slots", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"ranger", "sniper"}, Slots: []string{"discovery", "execution"}}, "role_slot_mismatch"},
		{"unsupported runtime", scaffoldSkillMD, SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"discovery"}, Runtime: "host"}, "runtime_unsupported"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := scaffoldPackage(t, tc.skill)
			tc.opts.PackageDir = dir

			_, err := ScaffoldSidecar(tc.opts)

			require.Error(t, err)
			assert.Equal(t, tc.code, scaffoldErrorCode(t, err))
			_, statErr := os.Stat(filepath.Join(dir, "strategist.yaml"))
			assert.True(t, os.IsNotExist(statErr), "a rejected declaration writes nothing")
		})
	}
}

func TestScaffoldSidecarNeverOverwritesWithoutForce(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)
	opts := SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}}
	_, err := ScaffoldSidecar(opts)
	require.NoError(t, err)

	again, err := ScaffoldSidecar(opts)
	require.NoError(t, err)
	assert.Equal(t, SidecarUnchanged, again.Status, "an identical regeneration leaves the file alone")

	path := filepath.Join(dir, "strategist.yaml")
	require.NoError(t, os.WriteFile(path, []byte("hand: edited\n"), 0o644))
	_, err = ScaffoldSidecar(opts)
	assert.Equal(t, "sidecar_exists_differs", scaffoldErrorCode(t, err))
	kept, readErr := os.ReadFile(path)
	require.NoError(t, readErr)
	assert.Equal(t, "hand: edited\n", string(kept))

	opts.Force = true
	forced, err := ScaffoldSidecar(opts)
	require.NoError(t, err)
	assert.Equal(t, SidecarOverwritten, forced.Status)
}

func TestScaffoldSidecarCheckReportsDriftWithoutWriting(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)
	opts := SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}}
	path := filepath.Join(dir, "strategist.yaml")

	opts.Check = true
	_, err := ScaffoldSidecar(opts)
	assert.Equal(t, "sidecar_drift", scaffoldErrorCode(t, err), "a missing sidecar is drift")
	_, statErr := os.Stat(path)
	assert.True(t, os.IsNotExist(statErr), "--check never writes")

	opts.Check = false
	_, err = ScaffoldSidecar(opts)
	require.NoError(t, err)
	opts.Check = true
	result, err := ScaffoldSidecar(opts)
	require.NoError(t, err)
	assert.Equal(t, SidecarUnchanged, result.Status)

	require.NoError(t, os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(scaffoldSkillMD+"changed\n"), 0o644))
	_, err = ScaffoldSidecar(opts)
	assert.Equal(t, "sidecar_drift", scaffoldErrorCode(t, err), "a changed package changes the input digest")
}

func TestScaffoldSidecarOutputIsDeterministic(t *testing.T) {
	first := scaffoldPackage(t, scaffoldSkillMD)
	second := scaffoldPackage(t, scaffoldSkillMD)
	opts := SidecarScaffoldOptions{Roles: []string{"ranger"}, Slots: []string{"discovery"}}

	opts.PackageDir = first
	_, err := ScaffoldSidecar(opts)
	require.NoError(t, err)
	opts.PackageDir = second
	_, err = ScaffoldSidecar(opts)
	require.NoError(t, err)

	a, _ := os.ReadFile(filepath.Join(first, "strategist.yaml"))
	b, _ := os.ReadFile(filepath.Join(second, "strategist.yaml"))
	assert.Equal(t, string(a), string(b))
}

func TestScaffoldSidecarProvenanceFillsOnlyWhatTheFileDeclares(t *testing.T) {
	dir := scaffoldPackage(t, scaffoldSkillMD)
	prov := filepath.Join(t.TempDir(), "provenance.yaml")
	require.NoError(t, os.WriteFile(prov, []byte("upstream_repo: acme/demo\nupstream_version: \"2.0.0\"\nlicense: MIT\n"), 0o644))

	_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}, ProvenancePath: prov})

	require.NoError(t, err)
	adapter, err := loadExternalSkillAdapter(dir, "demo-weapon")
	require.NoError(t, err)
	assert.Equal(t, "acme/demo", adapter.UpstreamRepo)
	assert.Equal(t, "2.0.0", adapter.UpstreamVersion)
	assert.Equal(t, "MIT", adapter.License)
	assert.Empty(t, adapter.UpstreamCommit)
	assert.Empty(t, adapter.UpstreamContentDigest)
}

func TestScaffoldSidecarRejectsAnInvalidProvenanceFile(t *testing.T) {
	for name, body := range map[string]string{
		"unknown key": "upstream_repo: a/b\nunexpected: 1\n",
		"not yaml":    "upstream_repo: [",
	} {
		t.Run(name, func(t *testing.T) {
			dir := scaffoldPackage(t, scaffoldSkillMD)
			prov := filepath.Join(t.TempDir(), "provenance.yaml")
			require.NoError(t, os.WriteFile(prov, []byte(body), 0o644))

			_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}, ProvenancePath: prov})

			assert.Equal(t, "provenance_invalid", scaffoldErrorCode(t, err))
		})
	}
	dir := scaffoldPackage(t, scaffoldSkillMD)
	_, err := ScaffoldSidecar(SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"ranger"}, Slots: []string{"discovery"}, ProvenancePath: filepath.Join(dir, "absent.yaml")})
	assert.Equal(t, "provenance_invalid", scaffoldErrorCode(t, err))
}

func TestScaffoldSidecarOpenSpecRootNeedsBundleAndDeclaredRuntime(t *testing.T) {
	opts := func(dir, prov string) SidecarScaffoldOptions {
		return SidecarScaffoldOptions{PackageDir: dir, Roles: []string{"archivist"}, Slots: []string{"refinement"}, Runtime: domain.RankedRuntimeOpenSpecRoot, ProvenancePath: prov}
	}
	runtimeProv := "runtime:\n  kind: openspec_root\n  root: .strategist/openspec\n  bootstrap: openspec init --profile core --tools codex\n  healthcheck: openspec context --json\n  version: 1.13.0\n  node_version: 22.23.2\n"
	writeProv := func(body string) string {
		p := filepath.Join(t.TempDir(), "provenance.yaml")
		require.NoError(t, os.WriteFile(p, []byte(body), 0o644))
		return p
	}

	t.Run("no bundle", func(t *testing.T) {
		dir := scaffoldPackage(t, scaffoldSkillMD)
		_, err := ScaffoldSidecar(opts(dir, writeProv(runtimeProv)))
		assert.Equal(t, "runtime_bundle_missing", scaffoldErrorCode(t, err))
	})

	t.Run("bundle without a declared runtime", func(t *testing.T) {
		dir := scaffoldPackage(t, scaffoldSkillMD)
		require.NoError(t, os.MkdirAll(filepath.Join(dir, "runtime"), 0o755))
		require.NoError(t, os.WriteFile(filepath.Join(dir, "runtime.lock.yaml"), []byte("schema_version: strategist-runtime-lock/v1\n"), 0o644))
		_, err := ScaffoldSidecar(opts(dir, ""))
		assert.Equal(t, "runtime_declaration_missing", scaffoldErrorCode(t, err))
	})

	t.Run("bundle and declared runtime", func(t *testing.T) {
		dir := scaffoldPackage(t, scaffoldSkillMD)
		require.NoError(t, os.MkdirAll(filepath.Join(dir, "runtime"), 0o755))
		require.NoError(t, os.WriteFile(filepath.Join(dir, "runtime.lock.yaml"), []byte("schema_version: strategist-runtime-lock/v1\n"), 0o644))
		_, err := ScaffoldSidecar(opts(dir, writeProv(runtimeProv)))
		require.NoError(t, err)
		var doc struct {
			Runtime     domain.WeaponRuntime `yaml:"runtime"`
			ScratchRoot string               `yaml:"scratch_root"`
		}
		raw, readErr := os.ReadFile(filepath.Join(dir, "strategist.yaml"))
		require.NoError(t, readErr)
		require.NoError(t, yaml.Unmarshal(raw, &doc))
		assert.Equal(t, "1.13.0", doc.Runtime.Version)
		assert.Equal(t, "runtime", doc.ScratchRoot)
	})
}
