package install

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"strings"

	"github.com/SergioLacerda/strategist-skill/internal/domain"
	"gopkg.in/yaml.v3"
)

// sidecarDocument fixes the key order of the generated strategist.yaml.
type sidecarDocument struct {
	Roles                 []string              `yaml:"roles"`
	CanonicalRole         string                `yaml:"canonical_role"`
	Version               string                `yaml:"version"`
	Kind                  domain.WeaponKind     `yaml:"kind"`
	SupportedSlots        []string              `yaml:"supported_slots"`
	Runtime               domain.WeaponRuntime  `yaml:"runtime"`
	RiskScore             string                `yaml:"risk_score"`
	Category              string                `yaml:"category"`
	Default               bool                  `yaml:"default,omitempty"`
	WeaponContract        domain.WeaponContract `yaml:"weapon_contract,omitempty"`
	ScratchRoot           string                `yaml:"scratch_root,omitempty"`
	UpstreamRepo          string                `yaml:"upstream_repo,omitempty"`
	UpstreamSkillPath     string                `yaml:"upstream_skill_path,omitempty"`
	UpstreamVersion       string                `yaml:"upstream_version,omitempty"`
	UpstreamCommit        string                `yaml:"upstream_commit,omitempty"`
	UpstreamContentDigest string                `yaml:"upstream_content_digest,omitempty"`
	License               string                `yaml:"license,omitempty"`
}

// rangerWeaponContract is the fixed contract a Weapon bound to the discovery
// Role must declare; other Roles omit it.
var rangerWeaponContract = domain.WeaponContract{
	RoleOwner: "ranger", Participation: "required", InvocationEvidence: "required",
	UnavailableBehavior: "role_invocation_failed", NativeSubstitution: "forbidden",
}

func renderSidecar(opts SidecarScaffoldOptions) ([]byte, error) {
	in, err := loadScaffoldInputs(opts)
	if err != nil {
		return nil, err
	}
	doc := sidecarDocumentFor(in, opts.Default)
	var body bytes.Buffer
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(doc); err != nil {
		return nil, fmt.Errorf("encode sidecar: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("encode sidecar: %w", err)
	}
	header := fmt.Sprintf("# Generated by strategist plugins scaffold-sidecar %s; inputs: %s\n", sidecarGeneratorVersion, scaffoldInputDigest(in, opts))
	if err := validateGeneratedSidecar(body.Bytes()); err != nil {
		return nil, err
	}
	return append([]byte(header), body.Bytes()...), nil
}

func sidecarDocumentFor(in scaffoldInputs, isDefault bool) sidecarDocument {
	doc := sidecarDocument{
		Roles: in.roles, CanonicalRole: in.roles[0], Version: in.version, Kind: domain.WeaponKindAtomic,
		SupportedSlots: in.slots, Runtime: in.runtime, RiskScore: in.riskScore, Category: in.slots[0],
		Default: isDefault, ScratchRoot: in.scratchRoot,
		UpstreamRepo: in.provenance.UpstreamRepo, UpstreamSkillPath: in.provenance.UpstreamSkillPath,
		UpstreamVersion: in.provenance.UpstreamVersion, UpstreamCommit: in.provenance.UpstreamCommit,
		UpstreamContentDigest: in.provenance.UpstreamContentDigest, License: in.provenance.License,
	}
	if in.roles[0] == "ranger" {
		doc.WeaponContract = rangerWeaponContract
	}
	return doc
}

// scaffoldInputDigest covers SKILL.md, the declared flags and the provenance
// bytes, so --check reports a changed package or declaration as drift.
func scaffoldInputDigest(in scaffoldInputs, opts SidecarScaffoldOptions) string {
	hash := sha256.New()
	for _, part := range [][]byte{
		in.skillMD,
		[]byte(strings.Join(in.roles, ",")),
		[]byte(strings.Join(in.slots, ",")),
		[]byte(in.runtime.Kind),
		[]byte(in.version),
		[]byte(fmt.Sprint(opts.Default)),
		in.provenanceRaw,
	} {
		_, _ = hash.Write(part)
		_, _ = hash.Write([]byte{0})
	}
	return fmt.Sprintf("sha256:%x", hash.Sum(nil))
}

// validateGeneratedSidecar loads the rendered YAML through the real ingestion
// adapter validation, so the generator can never emit a sidecar ingestion rejects.
func validateGeneratedSidecar(body []byte) error {
	var adapter externalSkillAdapter
	if err := yaml.Unmarshal(body, &adapter); err != nil {
		return scaffoldError("provenance_invalid", "generated sidecar does not parse: %v", err)
	}
	if err := validateExternalSkillAdapter("generated", adapter); err != nil {
		return scaffoldError("provenance_invalid", "generated sidecar is not ingestible: %v", err)
	}
	return nil
}
