#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT="${TAXONOMY_INVENTORY_OUT:-docs/generated/taxonomy-entity-inventory.yaml}"
mkdir -p "$(dirname "$OUT")"

python3 -c "import yaml" 2>/dev/null || {
  echo "generate-taxonomy-inventory: PyYAML is required" >&2
  exit 1
}

PYTHONIOENCODING=utf-8 python3 - "$OUT" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path

import yaml

out = Path(sys.argv[1])
root = Path.cwd()


def entity(family, entity_id, owner, source_paths, generated_paths, *, version="", lifecycle="active", provenance="embedded"):
    return {
        "family": family,
        "id": entity_id,
        **({"version": version} if version else {}),
        "owner": owner,
        "lifecycle": lifecycle,
        "provenance": provenance,
        "source_paths": sorted(source_paths),
        "generated_paths": sorted(generated_paths),
    }


entities = []
mechanisms_path = Path("internal/embed/defaults/contracts/machine/mechanisms.yaml")
mechanisms = yaml.safe_load(mechanisms_path.read_text(encoding="utf-8")) or {}
for row in mechanisms.get("mechanisms", []):
    entities.append(entity(
        row["family"], row["id"], row.get("owner_package") or "contracts",
        ["internal/embed/defaults/contracts/machine/mechanisms.yaml", "internal/mechanisms/registry.go"],
        [".strategist/contracts/machine/mechanisms.yaml", ".strategist/contracts/index.yaml"],
    ))

catalog_path = Path("internal/embed/defaults/plugins/catalog.yaml")
if catalog_path.exists():
    catalog = yaml.safe_load(catalog_path.read_text(encoding="utf-8")) or {}
    for weapon in catalog.get("weapons", []):
        entities.append(entity(
            "weapon", weapon["id"], "internal/plugins",
            ["internal/embed/defaults/plugins/catalog.yaml"],
            [".strategist/plugins.lock", ".strategist/plugins/catalog.yaml"],
            version=str(weapon.get("version", "")),
            provenance=str(weapon.get("origin", "embedded")),
        ))

for role in ("scout", "ranger", "archivist", "sniper"):
    entities.append(entity(
        "role", role, "internal/domain",
        ["internal/domain/role_registry.go", f"internal/embed/defaults/roles/{role}.yaml"],
        [f".strategist/roles/{role}.yaml"], provenance="native",
    ))

for stage in ("FULL", "SHORT", "ROSTER"):
    entities.append(entity(
        "stage", stage, "internal/domain",
        ["internal/domain/taxonomy_stage.go", "internal/domain/stage_resolution_artifact.go"],
        [".strategist/contracts/machine/scout-routing.yaml"], provenance="canonical",
    ))

artifact_sources = {
    "stage_resolution": "internal/domain/stage_resolution_artifact.go",
    "weapon_roster": "internal/domain/roster/roster_artifacts.go",
    "weapon_selection": "internal/domain/roster/roster_artifacts.go",
    "role_loadout": "internal/domain/role_loadout.go",
    "install_plan": "internal/domain/installplan/install_plan.go",
    "confidence_report": "internal/domain/confidence_report_artifact.go",
    "role_source": "internal/domain/role_source_artifact.go",
    "weapon_binding": "internal/domain/weapon_binding_artifacts.go",
}
artifact_owners = {
    "weapon_roster": "internal/domain/roster",
    "weapon_selection": "internal/domain/roster",
    "install_plan": "internal/domain/installplan",
}
for artifact_id, source in artifact_sources.items():
    entities.append(entity(
        "artifact", artifact_id, artifact_owners.get(artifact_id, "internal/domain"), [source],
        [".strategist/", "docs/generated/"], provenance="canonical",
    ))

deduped = {}
for item in entities:
    key = (item["family"], item["id"], item.get("version", ""))
    deduped[key] = item

families = ["role", "weapon", "feat", "tool", "mechanism", "stage", "artifact"]
doc = {
    "schema_version": "strategist-taxonomy-inventory/v1",
    "taxonomy_version": "strategist-taxonomy/v1",
    "authoritative_sources": {
        "embedded_authoring": "internal/embed/defaults/",
        "domain_contracts": "internal/domain/",
        "generated_runtime": ".strategist/",
        "canonical_adr": "docs/adr/0064-canonical-seven-family-taxonomy.md",
    },
    "forbidden_vocabulary": {
        "active_runtime_patterns": [
            "family: ability", "strategist.ability", "AbilityName",
            "FamilyAbility", "ability: initiative",
        ],
        "historical_exceptions": ["docs/adr/", "docs/plans/", "historical", "legacy"],
    },
    "families": families,
    "entities": sorted(deduped.values(), key=lambda item: (item["family"], item["id"], item.get("version", ""))),
}

out.write_text(
    "# Generated by scripts/generate-taxonomy-inventory.sh; do not edit manually.\n"
    + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
    encoding="utf-8",
)
print(f"generate-taxonomy-inventory: wrote {out}")
PY
