#!/usr/bin/env bash
# Shared provenance header for everything under docs/generated/.
# Sourced by scripts/generate-*.sh — never invoked directly.
#
# Reuses the HTML-comment provenance pattern already in production in
# internal/compile/agent_awareness.go (`<!-- generated by: ... — do not edit
# manually -->`), extended with explicit generated/source/generator/version
# fields per docs/adr/0025-generated-documentation-anti-drift.md.

# provenance_header <source-description> <generator-script-path>
# Prints an HTML-comment provenance block to stdout.
provenance_header() {
  local source_desc="$1"
  local generator_path="$2"
  cat <<EOF
<!--
generated: true
source: ${source_desc}
generator: ${generator_path}
generator_version: 1
do not edit manually — regenerate with: make docs-generate
-->
EOF
}
