#!/usr/bin/env bash
# sync-readme-coverage-badge.sh — rewrites the static Coverage badge in README.md
# from the measured value in coverage/coverage-badge.json (generated by
# generate-coverage-badge.sh, which is run first when the JSON is missing).
# Idempotent: running it twice yields the same README.
set -euo pipefail

readme="${README_FILE:-README.md}"
coverage_dir="${1:-coverage}"
go_cache="${2:-/tmp/go-build-cache}"
badge_json="$coverage_dir/coverage-badge.json"

if [[ ! -f "$readme" ]]; then
  echo "FAIL: $readme not found" >&2
  exit 1
fi
if [[ ! -f "$badge_json" ]]; then
  bash "$(dirname "$0")/generate-coverage-badge.sh" "$coverage_dir" "$go_cache" >/dev/null
fi

pct="$(grep -o '"message": *"[0-9.]*%' "$badge_json" | grep -o '[0-9.]*' | head -1)"
color="$(grep -o '"color": *"[a-z]*"' "$badge_json" | sed -E 's/.*"([a-z]+)"$/\1/')"
if [[ -z "$pct" || -z "$color" ]]; then
  echo "FAIL: could not read measured coverage from $badge_json" >&2
  exit 1
fi

sed -i -E "s#(img\\.shields\\.io/badge/coverage-)[0-9.]+%25-[a-z]+#\\1${pct}%25-${color}#" "$readme"
echo "sync-readme-coverage-badge: $readme coverage badge set to ${pct}% (${color})"
