//go:build spec

package spec_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// W7c: corpus reference & language lint over the authoring tree
// (internal/embed/defaults/). Guards the D4/D5/D8 defect classes found by the
// 2026-07-26 deep analysis: dot-less source-tree paths, references to files
// that do not exist at runtime, and non-English prose in the English-mandated
// corpus.

func corpusRoot(t *testing.T) string {
	t.Helper()
	return filepath.Join(repoRoot(t), "internal", "embed", "defaults")
}

func walkCorpusDocs(t *testing.T, fn func(path, content string)) {
	t.Helper()
	err := filepath.WalkDir(corpusRoot(t), func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		ext := filepath.Ext(path)
		if ext != ".md" && ext != ".yaml" {
			return nil
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		fn(path, string(data))
		return nil
	})
	if err != nil {
		t.Fatalf("walk corpus: %v", err)
	}
}

// D5 class: dot-less references to the retired source tree (strategist/<subpath>)
// are path drift by the skill's own path model — only .strategist/ is a valid
// runtime path prefix.
func TestCorpusHasNoDotlessSourceTreePaths(t *testing.T) {
	t.Parallel()

	// Forbid strategist/<known-subtree> when not preceded by "." (runtime tree)
	// or "/" (e.g. cmd/strategist/...).
	re := regexp.MustCompile(`(^|[^./\w])strategist/(contracts|schemas|templates|internal_skills|personas|roles|SKILL\.md|protocol\.md|skill\.yaml)`)
	walkCorpusDocs(t, func(path, content string) {
		for _, line := range strings.Split(content, "\n") {
			if m := re.FindString(line); m != "" {
				t.Errorf("%s: dot-less source-tree path %q (line: %.120s)", path, strings.TrimLeft(m, " `\"'(["), strings.TrimSpace(line))
			}
		}
	})
}

// D4 class: every .strategist/<file> reference in the two entry documents must
// exist in the authoring tree (which materializes 1:1 into .strategist/), except
// for allowlisted runtime-instance files that only exist after install/compile.
func TestEntryDocRuntimeReferencesResolve(t *testing.T) {
	t.Parallel()

	root := corpusRoot(t)
	runtimeOnly := []string{
		"agent-protocol.md", // generated by strategist compile
		"active.yaml",       // instance configuration
		"knowledge.index.yaml",
		"jewels.yaml",
	}
	re := regexp.MustCompile(`\.strategist/([A-Za-z0-9_\-./]+\.(?:md|yaml))`)

	for _, entry := range []string{
		filepath.Join(root, "SKILL.md"),
		filepath.Join(root, "templates", "agent-protocol.md"),
	} {
		content := readFile(t, entry)
		for _, m := range re.FindAllStringSubmatch(content, -1) {
			rel := m[1]
			skip := strings.Contains(rel, "memory/")
			for _, allow := range runtimeOnly {
				if rel == allow {
					skip = true
				}
			}
			if skip {
				continue
			}
			if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel))); err != nil {
				t.Errorf("%s references .strategist/%s which does not exist in the authoring tree", entry, rel)
			}
		}
	}
}

// D4: the two contract lookups that used to route through the protocol.md
// tombstone must point at anchors that actually exist in the target document.
func TestSkillContractPointersResolveToRealAnchors(t *testing.T) {
	t.Parallel()

	root := corpusRoot(t)
	skill := readFile(t, filepath.Join(root, "SKILL.md"))
	template := readFile(t, filepath.Join(root, "templates", "agent-protocol.md"))

	re := regexp.MustCompile("`?\\.strategist/(protocol\\.md|agent-protocol\\.md)#([a-z0-9-]+)`?")
	targets := map[string]string{
		"protocol.md":       readFile(t, filepath.Join(root, "protocol.md")),
		"agent-protocol.md": template,
	}
	anchorRe := regexp.MustCompile(`(?m)^#{1,6}\s+(.+)$`)
	slug := func(h string) string {
		h = strings.ToLower(strings.TrimSpace(h))
		h = regexp.MustCompile(`[^a-z0-9\s-]`).ReplaceAllString(h, "")
		return strings.ReplaceAll(regexp.MustCompile(`\s+`).ReplaceAllString(h, " "), " ", "-")
	}

	for _, m := range re.FindAllStringSubmatch(skill, -1) {
		doc, anchor := m[1], m[2]
		found := false
		for _, h := range anchorRe.FindAllStringSubmatch(targets[doc], -1) {
			if slug(h[1]) == anchor {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("SKILL.md references .strategist/%s#%s but no heading in %s slugs to that anchor", doc, anchor, doc)
		}
	}
}

// D8 class: Portuguese prose markers must not appear in the English-mandated
// corpus. Complements TestStrategistSourceTreeEnglishOnly with the markers from
// the 11-critical-hit.md leak found in the 2026-07-26 deep analysis.
func TestCorpusEnglishOnlyDeepAnalysisMarkers(t *testing.T) {
	t.Parallel()

	markers := []string{
		"A rota é selecionada",
		"re-avaliada",
		"delegatário",
		"missão em andamento",
	}
	walkCorpusDocs(t, func(path, content string) {
		for _, marker := range markers {
			if strings.Contains(content, marker) {
				t.Errorf("%s contains Portuguese prose marker %q (English-mandated corpus)", path, marker)
			}
		}
	})
}
